### ISSUE TITLE
Keresés a PDF-ben

### ISSUE THREAD

**Issue by drsandor** [ptrsimon/uni_notes#1]
Nem tudok ékezetes szövegre keresni a pdf-ben.  Javasolnám a main.tex fájlban cserélni ezt
`\usepackage{t1enc}`
erre
`\usepackage[T1]{fontenc}`
`\usepackage[utf8]{inputenc}`
Köszi

**Comment by ptrsimon** [comment]
Köszi az észrevételt, javítva: 9e6ae61f0bb2656b37f178f103a9484f58a8f38c
